config-main_parser
YungTatyu/webserv pull request #54
Opened 2024-01-28 03:03 UTC by YungTatyu

## 対応内容
- config main parserの実装
- contextのparse
→ http, events, server, location, limit_except

## 主にレビューして欲しいファイル
- Parser.cpp
- Parser.hpp
- test/conf/conf_parser_test.sh

2024-01-29 14:18 UTC, kohshi54 reviewed
ファイル数えぐいです笑笑
あとtestが現時点でfailしているのは想定内ですか？

2024-01-29 14:18 UTC, kohshi54 commented on src/config/Parser.cpp
> +		ret = &(this->config_.set_directives);
すごい今更なんですが、set_directivesが関数に見えちゃいます。
isDirectiveSetみたいの方がわかりやすいかなと思います。searchDirectiveSet()もgetDirctiveSetの方が分かりやすい気もします。

2024-01-29 15:10 UTC, YungTatyu commented on src/config/Parser.cpp
> +	return expect & actual;
この関数ではexpectのbitがactualにも立っているかを確認しています。

確かに引数の命名がわかりづらいですが、何かいい名前がありますか🤔

2024-01-29 15:12 UTC, YungTatyu commented on src/config/Parser.cpp
> +		}
REQUEST_METHOD(method)はキャストではなく、新たなインスタンスを生成しています。

2024-01-29 15:36 UTC, YungTatyu commented on src/config/Parser.cpp
> +		}
と思ったら要らなかったので、削除しました。

2024-01-29 15:53 UTC, kohshi54 commented on src/config/Parser.cpp
> +		ret = &(this->config_.set_directives);
directives_setいいですね。

なるほど〜
searchもfindもあんまり変わらなさそうなので、今のままでいいと思いました。

2024-01-29 15:54 UTC, YungTatyu commented on src/config/Parser.cpp
> +	while (this->tokens_[i].type_ != terminating_token)
current tokenのiteratorを取得する処理が二行使ってしまうので、一旦保留しました。

```
    std::vector<Token>::const_iterator begin_iterator = tokens_.begin();
    std::advance(begin_iterator, ti + 1);
```

スマートな書き方があれば、ご教示いただきたいです。

2024-01-29 16:04 UTC, kohshi54 commented on src/config/Parser.cpp
> +		ret = DELETE;
enum classでしかもC++11じゃないとダメなんんですね

2024-01-29 16:11 UTC, kohshi54 commented on src/config/Parser.cpp
> +	while (this->tokens_[i].type_ != terminating_token)
```cpp
std::vector<Token>::const_iterator start = tokens_.begin() + (this->ti + 1);
```
はどうですか？

2024-01-29 16:13 UTC, kohshi54 commented on src/config/Parser.cpp
> +	while (this->tokens_[i].type_ != terminating_token)
でもあれですね、C++98だとラムダ式も使えないから別途関数を用意する必要が出てくるのでfind_if使ってもイマイチだと思いました。言い出しといて何ですが今のままが良さそうです。

2024-01-29 16:15 UTC, YungTatyu commented on src/config/Parser.cpp
> +	for (std::vector<Location>::iterator it = list.begin(); it != list.end(); ++it)
単純な文字列の配列ではなく、it->uriメンバ変数を見ないといけないので、algorithmの関数が使えませんでした。（使いこなせなかった）
解決策ありますか？

```
for (std::vector<Location>::iterator it = list.begin(); it != list.end(); ++it)
	{
		if (it->uri_ == uri) // クラスのメンバ変数にアクセス
		{
			printError(std::string("duplicate location \"") + tokens[ti].value_ + "\"", tokens[ti]);
			return false;
		}
	}
```

2024-01-29 16:32 UTC, kohshi54 commented on src/config/Parser.cpp
> +	for (std::vector<Location>::iterator it = list.begin(); it != list.end(); ++it)
find_if(begin, end, func);
funcがuriかどうか見る関数
ってすればいける気がします

2024-01-29 16:34 UTC, kohshi54 approved these changes

2024-01-30 02:02 UTC, YungTatyu commented on src/config/Parser.cpp
> +	for (std::vector<Location>::iterator it = list.begin(); it != list.end(); ++it)
なるほど、
関数型プログラミングで使えますね

2024-01-30 02:17 UTC, YungTatyu commented on src/config/Parser.cpp
> +	return expect & actual;
コメントを追記することで対応するようにします。

2024-02-01 09:17 UTC, ayase-mstk reviewed
関数の前にまとめて説明書いてあるのがとてもわかりやすかったです。
contextによってどこに値入れるか分岐するやつがswitch文で書いてあってわかりやすかったです。僕もこれでやり直そうかな（笑）

2024-02-01 12:59 UTC, ayase-mstk commented on src/config/Parser.hpp
> +		size_t	ti; // token index
私もそのようにします。
対応ありがとうございます！

2024-02-01 14:48 UTC, ayase-mstk requested changes
対応ありがとうございました。

2024-02-01 14:49 UTC, ayase-mstk approved these changes
間違えました

2024-02-02 07:24 UTC, merged